<?php

// Legacy style code - DO NOT EDIT THIS FILE DIRECTLY
function calculate_price($items) {
    $total = 0;
    foreach ($items as $i) {
        // $i = ['type' => 'CLEANING', 'price' => 50, 'qty' => 1]
        if (!isset($i['price']) || !isset($i['qty'])) {
            continue;
        }
        $total += $i['price'] * $i['qty'];
    }

    // random "business rule"
    if ($total > 500) {
        // apply 5% discount
        $total = $total - ($total * 0.05);
    }

    return $total;
}
